import { Role, User } from '../types'
import { Resource, Resource_1, Ship } from './enum'

/**
 * 矿主
 */
export interface mineralHostConfig extends User {
  isMineralHost: boolean
  planetName: string
  level: number
  ships: Partial<Record<Ship, number>>
  resources_1: Partial<Record<Resource_1, number>>
}

export enum mineralHost {
  Hemara = 1,
  Vulcan,
  Phosryn,
  Mycthan,
  Obsythe,
  Cryne,
  Oreen,
  Nekthar,
}

export const mineralHostConfigs: Record<mineralHost, mineralHostConfig> = {
  [mineralHost.Hemara]: {
    id: 1,
    username: '赫玛拉',
    planetName: '曲室',
    level: 1,
    ships: {
      [Ship.LightHunter]: 10,
      [Ship.HeavyHunter]: 10,
    },
    registerTime: 995907,
    onlineTime: 995907,
    bannedTime: 0,
    safeMode: false,
    safeModeTime: 0,
    safeModeCount: 5,
    ip: '',
    universe: 1,
    planets: [],
    mainPlanetId: 0,
    avatarUrl: '',
    resources_3: {
      [Resource.DarkMatter]: 0,
      [Resource.AntiMatter]: 0,
      [Resource.StarDust]: 2,
      [Resource.Container]: 2,
    },
    resources_4: {
      [Resource.Aluminum]: 10,
      [Resource.Beryl]: 0,
      [Resource.TitaniumOre]: 0,
      [Resource.Emerald]: 0,
      [Resource.GoldMine]: 0,
      [Resource.Ruby]: 0,
      [Resource.Topaz]: 0,
      [Resource.IronOre]: 0,
    },
    battleStats: {
      win: 0,
      lose: 0,
      draw: 0,
    },
    technologies: {},
    technologiesQueue: [],
    officers: {},
    armories: {},
    ideologies: {},
    races: {},
    politicses: {},
    camps: {},
    mineralResearches: {},
    _bonus: {},
    products: {},
    signInTime: 0,
    messages: [],
    points: {
      total: 0,
      building: 0,
      technology: 0,
      ship: 0,
      defense: 0,
    },
    setting: {},
    expeditionLuck: {
      luckPoints: 0,
      consecutiveExpeditions: 0,
      pityCounter: 0,
      lastExpeditionTime: 0,
    },
    password: '',
    email: '',
    role: Role.User,
    isMineralHost: true,
    isBot: true,
    resources_1: {
      [Resource.Metal]: 1000000,
      [Resource.Crystal]: 1000000,
      [Resource.Deuterium]: 1000000,
    },
    isRealman: false,
  },
  [mineralHost.Vulcan]: {
    id: 2,
    username: '伏尔坎',
    planetName: '噬隙',
    level: 1,
    ships: {
      [Ship.HeavyHunter]: 5,
      [Ship.Crusher]: 10,
    },
    registerTime: 995907,
    onlineTime: 995907,
    bannedTime: 0,
    safeMode: false,
    safeModeTime: 0,
    safeModeCount: 5,
    ip: '',
    universe: 1,
    planets: [],
    mainPlanetId: 0,
    avatarUrl: '',
    resources_3: {
      [Resource.DarkMatter]: 0,
      [Resource.AntiMatter]: 0,
      [Resource.StarDust]: 2,
      [Resource.Container]: 1,
    },
    resources_4: {
      [Resource.Aluminum]: 0,
      [Resource.Beryl]: 1,
      [Resource.TitaniumOre]: 0,
      [Resource.Emerald]: 0,
      [Resource.GoldMine]: 0,
      [Resource.Ruby]: 0,
      [Resource.Topaz]: 0,
      [Resource.IronOre]: 0,
    },
    battleStats: {
      win: 0,
      lose: 0,
      draw: 0,
    },
    technologies: {},
    technologiesQueue: [],
    officers: {},
    armories: {},
    ideologies: {},
    races: {},
    politicses: {},
    camps: {},
    mineralResearches: {},
    _bonus: {},
    products: {},
    signInTime: 0,
    messages: [],
    points: {
      total: 0,
      building: 0,
      technology: 0,
      ship: 0,
      defense: 0,
    },
    setting: {},
    expeditionLuck: {
      luckPoints: 0,
      consecutiveExpeditions: 0,
      pityCounter: 0,
      lastExpeditionTime: 0,
    },
    password: '',
    email: '',
    role: Role.User,
    isMineralHost: true,
    isBot: true,
    resources_1: {
      [Resource.Metal]: 2000000,
      [Resource.Crystal]: 2000000,
      [Resource.Deuterium]: 2000000,
    },
    isRealman: false,
  },
  [mineralHost.Phosryn]: {
    id: 3,
    username: '弗斯林',
    planetName: '幻窗',
    level: 1,
    ships: {
      [Ship.Crusher]: 10,
      [Ship.BattleCruiser]: 10,
    },
    registerTime: 995907,
    onlineTime: 995907,
    bannedTime: 0,
    safeMode: false,
    safeModeTime: 0,
    safeModeCount: 5,
    ip: '',
    universe: 1,
    planets: [],
    mainPlanetId: 0,
    avatarUrl: '',
    resources_3: {
      [Resource.DarkMatter]: 0,
      [Resource.AntiMatter]: 0,
      [Resource.StarDust]: 2,
      [Resource.Container]: 2,
    },
    resources_4: {
      [Resource.Aluminum]: 0,
      [Resource.Beryl]: 0,
      [Resource.TitaniumOre]: 1,
      [Resource.Emerald]: 0,
      [Resource.GoldMine]: 0,
      [Resource.Ruby]: 0,
      [Resource.Topaz]: 0,
      [Resource.IronOre]: 0,
    },
    battleStats: {
      win: 0,
      lose: 0,
      draw: 0,
    },
    technologies: {},
    technologiesQueue: [],
    officers: {},
    armories: {},
    ideologies: {},
    races: {},
    politicses: {},
    camps: {},
    mineralResearches: {},
    _bonus: {},
    products: {},
    signInTime: 0,
    messages: [],
    points: {
      total: 0,
      building: 0,
      technology: 0,
      ship: 0,
      defense: 0,
    },
    setting: {},
    expeditionLuck: {
      luckPoints: 0,
      consecutiveExpeditions: 0,
      pityCounter: 0,
      lastExpeditionTime: 0,
    },
    password: '',
    email: '',
    role: Role.User,
    isMineralHost: true,
    isBot: true,
    resources_1: {
      [Resource.Metal]: 3000000,
      [Resource.Crystal]: 3000000,
      [Resource.Deuterium]: 3000000,
    },
    isRealman: false,
  },
  [mineralHost.Mycthan]: {
    id: 4,
    username: '密克桑',
    planetName: '逆境',
    level: 1,
    ships: {
      [Ship.BattleCruiser]: 10,
      [Ship.Battleship]: 10,
    },
    registerTime: 995907,
    onlineTime: 995907,
    bannedTime: 0,
    safeMode: false,
    safeModeTime: 0,
    safeModeCount: 5,
    ip: '',
    universe: 1,
    planets: [],
    mainPlanetId: 0,
    avatarUrl: '',
    resources_3: {
      [Resource.DarkMatter]: 0,
      [Resource.AntiMatter]: 0,
      [Resource.StarDust]: 2,
      [Resource.Container]: 1,
    },
    resources_4: {
      [Resource.Aluminum]: 0,
      [Resource.Beryl]: 0,
      [Resource.TitaniumOre]: 0,
      [Resource.Emerald]: 1,
      [Resource.GoldMine]: 0,
      [Resource.Ruby]: 0,
      [Resource.Topaz]: 0,
      [Resource.IronOre]: 0,
    },
    battleStats: {
      win: 0,
      lose: 0,
      draw: 0,
    },
    technologies: {},
    technologiesQueue: [],
    officers: {},
    armories: {},
    ideologies: {},
    races: {},
    politicses: {},
    camps: {},
    mineralResearches: {},
    _bonus: {},
    products: {},
    signInTime: 0,
    messages: [],
    points: {
      total: 0,
      building: 0,
      technology: 0,
      ship: 0,
      defense: 0,
    },
    setting: {},
    expeditionLuck: {
      luckPoints: 0,
      consecutiveExpeditions: 0,
      pityCounter: 0,
      lastExpeditionTime: 0,
    },
    password: '',
    email: '',
    role: Role.User,
    isMineralHost: true,
    isBot: true,
    resources_1: {
      [Resource.Metal]: 4000000,
      [Resource.Crystal]: 4000000,
      [Resource.Deuterium]: 4000000,
    },
    isRealman: false,
  },
  [mineralHost.Obsythe]: {
    id: 5,
    username: '奥赛斯',
    planetName: '逝廊',
    level: 1,
    ships: {
      [Ship.LightHunter]: 80,
      [Ship.Battleship]: 100,
    },
    registerTime: 995907,
    onlineTime: 995907,
    bannedTime: 0,
    safeMode: false,
    safeModeTime: 0,
    safeModeCount: 5,
    ip: '',
    universe: 1,
    planets: [],
    mainPlanetId: 0,
    avatarUrl: '',
    resources_3: {
      [Resource.DarkMatter]: 0,
      [Resource.AntiMatter]: 0,
      [Resource.StarDust]: 2,
      [Resource.Container]: 1,
    },
    resources_4: {
      [Resource.Aluminum]: 0,
      [Resource.Beryl]: 0,
      [Resource.TitaniumOre]: 0,
      [Resource.Emerald]: 0,
      [Resource.GoldMine]: 1,
      [Resource.Ruby]: 0,
      [Resource.Topaz]: 0,
      [Resource.IronOre]: 0,
    },
    battleStats: {
      win: 0,
      lose: 0,
      draw: 0,
    },
    technologies: {},
    technologiesQueue: [],
    officers: {},
    armories: {},
    ideologies: {},
    races: {},
    politicses: {},
    camps: {},
    mineralResearches: {},
    _bonus: {},
    products: {},
    signInTime: 0,
    messages: [],
    points: {
      total: 0,
      building: 0,
      technology: 0,
      ship: 0,
      defense: 0,
    },
    setting: {},
    expeditionLuck: {
      luckPoints: 0,
      consecutiveExpeditions: 0,
      pityCounter: 0,
      lastExpeditionTime: 0,
    },
    password: '',
    email: '',
    role: Role.User,
    isMineralHost: true,
    isBot: true,
    resources_1: {
      [Resource.Metal]: 10000000,
      [Resource.Crystal]: 10000000,
      [Resource.Deuterium]: 10000000,
    },
    isRealman: false,
  },
  [mineralHost.Cryne]: {
    id: 6,
    username: '克雷涅',
    planetName: '虚匣',
    level: 1,
    ships: {
      [Ship.HeavyHunter]: 2000,
      [Ship.BattleCruiser]: 1000,
    },
    registerTime: 995907,
    onlineTime: 995907,
    bannedTime: 0,
    safeMode: false,
    safeModeTime: 0,
    safeModeCount: 5,
    ip: '',
    universe: 1,
    planets: [],
    mainPlanetId: 0,
    avatarUrl: '',
    resources_3: {
      [Resource.DarkMatter]: 0,
      [Resource.AntiMatter]: 0,
      [Resource.StarDust]: 2,
      [Resource.Container]: 1,
    },
    resources_4: {
      [Resource.Aluminum]: 0,
      [Resource.Beryl]: 0,
      [Resource.TitaniumOre]: 0,
      [Resource.Emerald]: 0,
      [Resource.GoldMine]: 0,
      [Resource.Ruby]: 1,
      [Resource.Topaz]: 0,
      [Resource.IronOre]: 0,
    },
    battleStats: {
      win: 0,
      lose: 0,
      draw: 0,
    },
    technologies: {},
    technologiesQueue: [],
    officers: {},
    armories: {},
    ideologies: {},
    races: {},
    politicses: {},
    camps: {},
    mineralResearches: {},
    _bonus: {},
    products: {},
    signInTime: 0,
    messages: [],
    points: {
      total: 0,
      building: 0,
      technology: 0,
      ship: 0,
      defense: 0,
    },
    setting: {},
    expeditionLuck: {
      luckPoints: 0,
      consecutiveExpeditions: 0,
      pityCounter: 0,
      lastExpeditionTime: 0,
    },
    password: '',
    email: '',
    role: Role.User,
    isMineralHost: true,
    isBot: true,
    resources_1: {
      [Resource.Metal]: 50000000,
      [Resource.Crystal]: 50000000,
      [Resource.Deuterium]: 50000000,
    },
    isRealman: false,
  },
  [mineralHost.Oreen]: {
    id: 7,
    username: '奥里恩',
    planetName: '谎门',
    level: 1,
    ships: {
      [Ship.LightHunter]: 2000,
      [Ship.Crusher]: 3000,
    },
    registerTime: 995907,
    onlineTime: 995907,
    bannedTime: 0,
    safeMode: false,
    safeModeTime: 0,
    safeModeCount: 5,
    ip: '',
    universe: 1,
    planets: [],
    mainPlanetId: 0,
    avatarUrl: '',
    resources_3: {
      [Resource.DarkMatter]: 0,
      [Resource.AntiMatter]: 0,
      [Resource.StarDust]: 2,
      [Resource.Container]: 1,
    },
    resources_4: {
      [Resource.Aluminum]: 0,
      [Resource.Beryl]: 0,
      [Resource.TitaniumOre]: 0,
      [Resource.Emerald]: 0,
      [Resource.GoldMine]: 0,
      [Resource.Ruby]: 0,
      [Resource.Topaz]: 1,
      [Resource.IronOre]: 0,
    },
    battleStats: {
      win: 0,
      lose: 0,
      draw: 0,
    },
    technologies: {},
    technologiesQueue: [],
    officers: {},
    armories: {},
    ideologies: {},
    races: {},
    politicses: {},
    camps: {},
    mineralResearches: {},
    _bonus: {},
    products: {},
    signInTime: 0,
    messages: [],
    points: {
      total: 0,
      building: 0,
      technology: 0,
      ship: 0,
      defense: 0,
    },
    setting: {},
    expeditionLuck: {
      luckPoints: 0,
      consecutiveExpeditions: 0,
      pityCounter: 0,
      lastExpeditionTime: 0,
    },
    password: '',
    email: '',
    role: Role.User,
    isMineralHost: true,
    isBot: true,
    resources_1: {
      [Resource.Metal]: 100000000,
      [Resource.Crystal]: 100000000,
      [Resource.Deuterium]: 100000000,
    },
    isRealman: false,
  },
  [mineralHost.Nekthar]: {
    id: 8,
    username: '涅克萨',
    planetName: '殁刻',
    level: 1,
    ships: {
      [Ship.LightHunter]: 30000,
      [Ship.BattleCruiser]: 20000,
    },
    registerTime: 995907,
    onlineTime: 995907,
    bannedTime: 0,
    safeMode: false,
    safeModeTime: 0,
    safeModeCount: 5,
    ip: '',
    universe: 1,
    planets: [],
    mainPlanetId: 0,
    avatarUrl: '',
    resources_3: {
      [Resource.DarkMatter]: 0,
      [Resource.AntiMatter]: 0,
      [Resource.StarDust]: 2,
      [Resource.Container]: 1,
    },
    resources_4: {
      [Resource.Aluminum]: 0,
      [Resource.Beryl]: 0,
      [Resource.TitaniumOre]: 0,
      [Resource.Emerald]: 0,
      [Resource.GoldMine]: 0,
      [Resource.Ruby]: 0,
      [Resource.Topaz]: 0,
      [Resource.IronOre]: 1,
    },
    battleStats: {
      win: 0,
      lose: 0,
      draw: 0,
    },
    technologies: {},
    technologiesQueue: [],
    officers: {},
    armories: {},
    ideologies: {},
    races: {},
    politicses: {},
    camps: {},
    mineralResearches: {},
    _bonus: {},
    products: {},
    signInTime: 0,
    messages: [],
    points: {
      total: 0,
      building: 0,
      technology: 0,
      ship: 0,
      defense: 0,
    },
    setting: {},
    expeditionLuck: {
      luckPoints: 0,
      consecutiveExpeditions: 0,
      pityCounter: 0,
      lastExpeditionTime: 0,
    },
    password: '',
    email: '',
    role: Role.User,
    isMineralHost: true,
    isBot: true,
    resources_1: {
      [Resource.Metal]: 5000000000,
      [Resource.Crystal]: 5000000000,
      [Resource.Deuterium]: 5000000000,
    },
    isRealman: false,
  },
}
